seed: 42

# each kernel variable has dim (t, lat, lon), t is yyyy-mm
dataset:
  era5: # data that the era5 monthly single level data will be in
    path: './data/era5_processed'
  kernels: # data that the kernel data will be in
    path: './data/kernels'
  years: # even years from 1990-2020
    # - 1990
    # - 1992
    # - 1994
    # - 1996
    # - 1998
    # - 2000
    # - 2002
    # - 2004
    - 2006
    - 2008
    # - 2010
    # - 2012
    # - 2014
    # - 2016
    # - 2018
    # - 2020

model:
  input_dim: 7
  hidden_dim: 15

optimizer:
  learning_rate: 0.001

train:
  epochs: 100
  checkpoint_dir: './baseline-simple'
  split_ratio: 0.8
  batch_size: 256

wandb:
  project: 'climate-feedback-solobev'
  entity: 'baseline-simple'
