base: 1990-2020_1-12_baseline.yaml

model:
  activation: "relu"

train:
  name: "1990-2020_1-12_baseline_relu"
  checkpoint_dir: "./checkpoints/ts/1990-2020_1-12_baseline_relu"
  sobolev: False
  sobolev_vars: []

preprocess:
  params_dir: 'preprocess_states/ts/baseline'
  ecod:
    enabled: True
    method: "true"
