base: ../../base/model/common.yaml

dataset:
  input_vars:
    - skt
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - ecod
  kernel_vars:
    - skt
  target_var: "ttr"
  months:
    - 3
    - 9
  era5:
    path: "./data/ts/era5_processed_mar_sep_2011_2014"
  kernels:
    raw_path: "./data/ts/kernels"
    path: "./data/ts/kernels_processed_mar_sep_2011_2014"
  train_years:
    - 2011
    - 2012
    - 2013
    - 2014
  val_years:
    - 2015
  test_years:
    - 2015

preprocess:
  params_dir: "preprocess_states/ts/2011-2014_3,9"
  ecod:
    enabled: True
    method: "true"

model:
  input_dim: 9
  hidden_dim_sizes:
    - 11

train:
  name: "2011-2014_3,9_sob_skt"
  checkpoint_dir: "./checkpoints/ts/2011-2014_3,9_sob_skt"
  sobolev: True
  sobolev_vars:
    - skt
  sobolev_alpha: 0.5
