base: ../../base/model/common.yaml

dataset:
  input_vars:
    - skt
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - ecod
  clear_sky_zero_vars:
    - hcc
    - mcc
    - lcc
    - tciw
    - tclw
    - ecod
  input_var: "skt"
  target_var: "ttr"
  era5:
    path: "./data/ts/era5_processed"
  kernels:
    raw_path: "./data/ts/kernels"
    path: "./data/ts/kernels_processed"
  train_years:
    - 2011
    - 2012
    - 2013
    - 2014
  val_years:
    - 2015
  test_years:
    - 2015

preprocess:
  params_dir: "preprocess_states/ts/baseline_2011_2014"
  ecod: True

model:
  input_dim: 9
  hidden_dim_sizes:
    - 11

train:
  name: "2011-2014_baseline"
  checkpoint_dir: "./checkpoints/ts/2011-2014_baseline"
  sobolev: False
  sobolev_vars: []
