base: ../../base/model/common.yaml

dataset:
  input_vars:
    - skt
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - ecod
  clear_sky_zero_vars:
    - hcc
    - mcc
    - lcc
    - tciw
    - tclw
    - ecod
  input_var: "skt"
  target_var: "ttr"
  era5:
    path: './data/ts/era5_processed'
  kernels:
    raw_path: "./data/ts/kernels"
    path: './data/ts/kernels_processed'

preprocess:
  params_dir: 'preprocess_states/ts/baseline'
  ecod: True

model:
  input_dim: 9
  hidden_dim_sizes:
    - 11

train:
  name: "ts_baseline"
  checkpoint_dir: "./checkpoints/ts/baseline"
  sobolev: False
  sobolev_vars: []