base: baseline.yaml

model:
  activation: "relu"

train:
  name: "ts_baseline_relu"
  checkpoint_dir: "./checkpoints/ts/baseline_relu"
  sobolev: False

preprocess:
  params_dir: 'preprocess_states/ts/baseline'
  ecod: True
