base: ../../base/model/common.yaml

dataset:
  input_vars:
    - skt
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - tisr
    - ecod
  input_var: "skt"
  target_var: "ttr"
  months:
    - 3
    - 9
  era5:
    path: "./data/ts/era5_processed_mar_sep"
  kernels:
    raw_path: "./data/ts/kernels"
    path: "./data/ts/kernels_processed_mar_sep"

preprocess:
  params_dir: "preprocess_states/ts/baseline_mar_sep"
  ecod: True

model:
  input_dim: 10
  hidden_dim_sizes:
    - 11

train:
  name: "ts_baseline_mar_sep"
  checkpoint_dir: "./checkpoints/ts/baseline_mar_sep"
  sobolev: False
