base: ../../base/model/common.yaml

dataset:
  era5:
    path: './data/ts/era5_processed'
  kernels:
    path: './data/ts/kernels_processed'

preprocess:
  params_dir: 'preprocess_states/ts/baseline'
  ecod: True

optimizer:
  scheduler:
    type: cosine_annealing
    t_max: 100
    eta_min: 1.0e-6

model:
  input_dim: 11
  hidden_dim_sizes:
    - 11

train:
  name: "ts_baseline_cos"
  checkpoint_dir: './checkpoints/ts/baseline_cosine_annealing'
  sobolev: False
