base: ../../base/model/common.yaml

dataset:
  era5:
    path: './data/ts/era5_processed'
  kernels:
    input_var: "skt"
    type: "ts"
    path: './data/ts/kernels_processed'

preprocess:
  name: "ts_preprocessor"
  params_dir: 'preprocess_states/ts/baseline'
  ecod: True

model:
  input_dim: 11
  hidden_dim_sizes:
    - 11

train:
  name: "ts_baseline"
  checkpoint_dir: "./checkpoints/ts/baseline"
  sobolev: False