base: ../../base/model/common.yaml

dataset:
  era5:
    path: "./data/ts/era5_processed"
  kernels:
    input_var: "skt"
    type: "ts"
    path: "./data/ts/kernels_processed"
  train_years:
    - 2011
    - 2012
    - 2013
    - 2014
  val_years:
    - 2015
  test_years:
    - 2015

preprocess:
  name: "ts_preprocessor"
  params_dir: "preprocess_states/ts/baseline_2011_2014"
  ecod: True

model:
  input_dim: 11
  hidden_dim_sizes:
    - 11

train:
  name: "ts_sob_cld_2011_2014"
  checkpoint_dir: "./checkpoints/ts/sob_cld_2011_2014"
  sobolev: "cld"
  sobolev_alpha: 0.5
