seed: 42

dataset:
  era5:
    raw_path: './data/era5'
  kernels:
    raw_path: './data/kernels'
  train_years:
    - 1990
    - 1992
    - 1994
    - 1996
    - 1998
    - 2000
    - 2002
    - 2004
    - 2006
    - 2008
    - 2010
    - 2012
    - 2014
    - 2016
    - 2018
    - 2020
  val_years:
    - 1997
    - 2005
    - 2013
  test_years:
    - 1991
    - 1993
    - 1995
    - 1997
    - 1999
    - 2001
    - 2003
    - 2005
    - 2007
    - 2009
    - 2011
    - 2013
    - 2015
    - 2017
    - 2019

optimizer:
  learning_rate: 0.001

model:
  activation: "tanh"

train:
  max_epochs_without_improvement: 10
  early_stopping_threshold: 0.001
  epochs: 100
  batch_size: 256

wandb:
  project: 'climate-feedback-sobolev'
  entity: 'ezrah442'
