base: ../base/model/common.yaml

dataset:
  era5:
    path: './data/era5_processed'
  kernels:
    path: './data/kernels_processed'

preprocess:
  params_dir: 'preprocess_states/baseline'

optimizer:
  scheduler:
    type: cosine_annealing
    t_max: 900
    eta_min: 1.0e-6

model:
  input_dim: 12
  hidden_dim_sizes:
    - 11

train:
  name: "baseline_cos"
  checkpoint_dir: './checkpoints/baseline_cosine_annealing'
  sobolev: False
