base: ../base/model/common.yaml

dataset:
  months:
    - 3
    - 9
  era5:
    path: "./data/era5_processed_mar_sep"
  kernels:
    path: "./data/kernels_processed_mar_sep"

preprocess:
  params_dir: "preprocess_states/baseline_mar_sep"
  ecod: True

model:
  input_dim: 12
  hidden_dim_sizes:
    - 11

train:
  name: "baseline_mar_sep"
  checkpoint_dir: "./checkpoints/baseline_mar_sep"
  sobolev: False
