base: baseline.yaml

model:
  activation: "relu"

train:
  name: "baseline_relu"
  checkpoint_dir: "./checkpoints/baseline_relu"
  sobolev: False

preprocess:
  params_dir: 'preprocess_states/baseline_no_ecod'
  ecod: True
