base: ../base/model/common.yaml

dataset:
  era5:
    path: "./data/era5_processed_no_ecod"
  kernels:
    path: "./data/kernels_processed_no_ecod"

preprocess:
  params_dir: 'preprocess_states/baseline_no_ecod'

model:
  input_dim: 10
  hidden_dim_sizes:
    - 11

train:
  name: "baseline_no_ecod"
  checkpoint_dir: "./checkpoints/baseline_no_ecod"
  sobolev: False