base: ../../base/preprocess/common.yaml

dataset:
  months:
    - 3
    - 9
  era5:
    path: "./data/ts/era5_processed_mar_sep"
  kernels:
    path: "./data/ts/kernels_processed_mar_sep"

preprocess:
  params_dir: "preprocess_states/ts/baseline_mar_sep"
  ecod: True
