base: ../../base/preprocess/common.yaml

dataset:
  input_vars:
    - skt
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - ecod
  target_var: "ttr"
  months:
    - 3
    - 9
  era5:
    path: "./data/ts/era5_processed_mar_sep"
  kernels:
    raw_path: "./data/ts/kernels"
    path: "./data/ts/kernels_processed_mar_sep"

preprocess:
  params_dir: "preprocess_states/ts/baseline_mar_sep"
  ecod:
    enabled: True
    method: "true"
