base: ../../base/preprocess/common.yaml

dataset:
  era5:
    path: './data/ts/era5_processed'
  kernels:
    path: './data/ts/kernels_processed'

preprocess:
  params_dir: 'preprocess_states/ts/baseline'
  ecod: True