base: 2011-2014_3,6,9,12.yaml

dataset:
  era5:
    path: "./data/fal/era5_processed_mar_june_sep_dec_2011_2014_true_tcc_ecod"
  kernels:
    path: "./data/fal/kernels_processed_mar_june_sep_dec_2011_2014_true_tcc_ecod"

preprocess:
  params_dir: "preprocess_states/fal/2011-2014_3,6,9,12_true_tcc_ecod"
  ecod:
    method: "true_tcc"
