base: ../../base/preprocess/common.yaml

dataset:
  era5:
    path: './data/fal/era5_processed'
  kernels:
    path: './data/fal/kernels_processed'

preprocess:
  params_dir: 'preprocess_states/fal/baseline'
  ecod: True