base: ../../base/preprocess/common.yaml

dataset:
  era5:
    path: "./data/fal/era5_processed_no_ecod"
  kernels:
    path: "./data/fal/kernels_processed_no_ecod"

preprocess:
  params_dir: "preprocess_states/fal/baseline_no_ecod"
  ecod: False