base: ../../base/model/common.yaml

dataset:
  input_vars:
    - fal
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - tisr
    - ecod
    - ecod_fal
  clear_sky_zero_vars:
    - hcc
    - mcc
    - lcc
    - tciw
    - tclw
    - ecod
    - ecod_fal
  era5:
    path: './data/fal/era5_processed'
  kernels:
    raw_path: "./data/fal/kernels"
    path: './data/fal/kernels_processed'

preprocess:
  params_dir: 'preprocess_states/fal/baseline'
  ecod:
    enabled: True
    method: "true"

model:
  input_dim: 11
  hidden_dim_sizes:
    - 11

train:
  name: "1990-2020_1-12_baseline"
  checkpoint_dir: "./checkpoints/fal/1990-2020_1-12_baseline"
  sobolev: False
  sobolev_vars: []
