base: ../../base/model/common.yaml

dataset:
  input_vars:
    - fal
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - tisr
  clear_sky_zero_vars:
    - hcc
    - mcc
    - lcc
    - tciw
    - tclw
  era5:
    path: "./data/fal/era5_processed_no_ecod"
  kernels:
    raw_path: "./data/fal/kernels"
    path: "./data/fal/kernels_processed_no_ecod"

preprocess:
  params_dir: 'preprocess_states/fal/baseline_no_ecod'
  ecod:
    enabled: False
    method: "true"

model:
  input_dim: 9
  hidden_dim_sizes:
    - 11

train:
  name: "1990-2020_1-12_baseline_no_ecod"
  checkpoint_dir: "./checkpoints/fal/1990-2020_1-12_baseline_no_ecod"
  sobolev: False
  sobolev_vars: []
