base: ../../base/model/common.yaml

dataset:
  input_vars:
    - fal
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - tisr
    - ecod
    - ecod_fal
  clear_sky_zero_vars:
    - hcc
    - mcc
    - lcc
    - tciw
    - tclw
    - ecod
    - ecod_fal
  months:
    - 3
    - 6
    - 9
    - 12
  era5:
    path: "./data/fal/era5_processed_mar_june_sep_dec_2011_2014"
  kernels:
    raw_path: "./data/fal/kernels"
    path: "./data/fal/kernels_processed_mar_june_sep_dec_2011_2014"
  train_years:
    - 2011
    - 2012
    - 2013
    - 2014
  val_years:
    - 2015
  test_years:
    - 2015

preprocess:
  params_dir: "preprocess_states/fal/baseline_mar_june_sep_dec_2011_2014"
  ecod:
    enabled: True
    method: "true"

model:
  input_dim: 11
  hidden_dim_sizes:
    - 11

train:
  name: "2011-2014_3,6,9,12_sob_fal"
  checkpoint_dir: "./checkpoints/fal/2011-2014_3,6,9,12_sob_fal"
  sobolev: True
  sobolev_vars:
    - fal
  sobolev_alpha: 0.5
