base: ../../base/model/common.yaml

dataset:
  input_vars:
    - fal
    - hcc
    - mcc
    - lcc
    - sp
    - tciw
    - tclw
    - tcwv
    - tco3
    - tisr
    - ecod
    - ecod_fal
  kernel_vars: ['fal']
  sky: ['all', 'clear']
  months: [3, 6, 9, 12]
  era5:
    path: './data/fal/era5_processed_mar_june_sep_dec_2011_2014_clearsky_fast_ecod'
  kernels:
    raw_path: './data/fal/kernels'
    path: './data/fal/kernels_processed_mar_june_sep_dec_2011_2014_clearsky_fast_ecod'
  train_years: [2011, 2012, 2013, 2014]
  val_years: [2015]
  test_years: [2015]

preprocess:
  params_dir: 'preprocess_states/fal/2011-2014_3,6,9,12_clearsky_fast_ecod'
  ecod:
    enabled: True
    method: 'fast'

model:
  input_dim: 12
  hidden_dim_sizes: [11]

train:
  name: '2011-2014_3,6,9,12_sob_fal_clearsky_fast_ecod'
  checkpoint_dir: './checkpoints/fal/2011-2014_3,6,9,12_sob_fal_clearsky_fast_ecod'
  sobolev: True
  sobolev_vars:
    - fal
  sobolev_alpha: 0.5
