base: baseline.yaml

model:
  activation: "relu"

train:
  name: "baseline_relu"
  checkpoint_dir: "./checkpoints/fal/baseline_relu"
  sobolev: False

preprocess:
  name: "2024_preprocessor"
  params_dir: 'preprocess_states/fal/baseline'
  ecod: True
